### ISSUE TITLE
Include DAViCal unit tests 

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud-archive/acceptance-testing#1]
Let's see which test cases DAViCal has and maybe include them here as well.

**Comment by DeepDiver1975** [comment]
http://trac.calendarserver.org/wiki/CalDAVTester

**Comment by butonic** [comment]
Just had a quick look:
1. clone CalDavTester with `git clone git://git.calendarserver.org/calendarserver/CalDAVTester.git`
2. configured `scripts/server/serverinfo.xml`:

``` patch
diff --git a/scripts/server/serverinfo.xml b/scripts/server/serverinfo.xml
index b7d4f09..f4c1f61 100644
--- a/scripts/server/serverinfo.xml
+++ b/scripts/server/serverinfo.xml
@@ -20,8 +20,8 @@

 <serverinfo>
    <host>localhost</host>
-   <nonsslport>8008</nonsslport>
-   <sslport>8443</sslport>
+   <nonsslport>80</nonsslport>
+   <sslport>443</sslport>
    <authtype>basic</authtype>

    <features>
@@ -38,7 +38,7 @@
        <feature>principal-search-property-set REPORT</feature> <!-- ACL principal-search-property-set REPORT -->

        <feature>add-member</feature>                   <!-- Add-member used to create resources -->
-       <!-- <feature>auth-on-root</feature> -->        <!-- Whether the server requires authentication on the root URI -->
+       <feature>auth-on-root</feature>     <!-- Whether the server requires authentication on the root URI -->
        <feature>brief</feature>                        <!-- Brief header for PROPFIND, REPORT -->
        <feature>bulk-post</feature>                    <!-- Bulk POST requests -->
        <feature>ctag</feature>                         <!-- ctag extension -->
@@ -156,7 +156,7 @@
        <!-- relative path to caldav root-->
        <substitution>
            <key>$root:</key>
-           <value>/</value>
+           <value>core/remote.php/caldav/</value>
        </substitution>

        <!-- relative path to main principal collection-->
```
1. install subversion `apt-get install subversion` because the next step then automagically fetches deps
2. execute the tests from the CalDavTester directory with ./run.py

I get lots of failed tests but also some working. The config file still has lots of options to change and I'd start with the `$calendars_uids:` key, because it inserts `__uids__` in the url .... might need some more tweaking but I don't know when we would leave interoperability with clients.

@georgehrke have you tried to test the owncloud calendar app / caldav with this testsuite?

**Comment by georgehrke** [comment]
> @georgehrke have you tried to test the owncloud calendar app / caldav with this testsuite?

Not yet, but I'll definitely give it a try.

**Comment by georgehrke** [comment]
they test quite a lot of extensions we have not implemented. Our first goal should be to get a 100% score on the basic caldav test

**Comment by georgehrke** [comment]
The tests are calling strange urls like 

```
/ownCloud6/remote.php/caldav/calendars/$uidstype:/user01/calendar/1.ics
```

That's the reason why a lot of tests fail.
While running a basic set of tests, the server returns **24**x 400 and **275**x 401.

That's probably just a config issue with caldavtester
